group: travis_latest
language: python
cache: pip
python:
    - 3.6
install:
    - pip install flake8  # pytest  # add another testing frameworks later
before_script:
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --select=E501,E9,F821,F822,F823,W191 --show-source --statistics
    # exit-zero treats all errors as warnings.
    - flake8 . --count --exit-zero --max-complexity=10 --statistics
script:
    - true  # pytest --capture=sys  # add other tests here
notifications:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down
