dist: trusty
sudo: required
language: python
cache: pip
python:
    - "3.5"
    - "3.6"
    - "3.7"
before_install:
    - sudo apt-get update
    - sudo apt-get install -y libmpv1
    - pip install pyflakes
    - pyflakes .
install: pip install .
script: comp -v